#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinFormsWithShinobiCharts.Android.Resource", IsApplication=true)]

namespace XamarinFormsWithShinobiCharts.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000f
			public const int sc_alternateGridStripeColor = 2130771983;
			
			// aapt resource value: 0x7f010048
			public const int sc_annotationBackgroundColor = 2130772040;
			
			// aapt resource value: 0x7f010049
			public const int sc_annotationTextColor = 2130772041;
			
			// aapt resource value: 0x7f01004a
			public const int sc_annotationTextSize = 2130772042;
			
			// aapt resource value: 0x7f010007
			public const int sc_axisLineColor = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int sc_axisTitleColor = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int sc_axisTitleTextSize = 2130771974;
			
			// aapt resource value: 0x7f010046
			public const int sc_bandSeriesAreaColor = 2130772038;
			
			// aapt resource value: 0x7f010047
			public const int sc_bandSeriesAreaInvertedColor = 2130772039;
			
			// aapt resource value: 0x7f010044
			public const int sc_bandSeriesHighColor = 2130772036;
			
			// aapt resource value: 0x7f010045
			public const int sc_bandSeriesLowColor = 2130772037;
			
			// aapt resource value: 0x7f010020
			public const int sc_barLineWidth = 2130772000;
			
			// aapt resource value: 0x7f010001
			public const int sc_chartBackgroundColor = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int sc_chartTitleColor = 2130771968;
			
			// aapt resource value: 0x7f01001f
			public const int sc_columnLineWidth = 2130771999;
			
			// aapt resource value: 0x7f010013
			public const int sc_crosshairLineColor = 2130771987;
			
			// aapt resource value: 0x7f010018
			public const int sc_crosshairLineWidth = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int sc_crosshairPadding = 2130771993;
			
			// aapt resource value: 0x7f010016
			public const int sc_crosshairTooltipBackgroundColor = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int sc_crosshairTooltipBorderColor = 2130771991;
			
			// aapt resource value: 0x7f01001c
			public const int sc_crosshairTooltipBorderWidth = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public const int sc_crosshairTooltipCornerRadius = 2130771995;
			
			// aapt resource value: 0x7f010015
			public const int sc_crosshairTooltipLabelBackgroundColor = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int sc_crosshairTooltipTextColor = 2130771988;
			
			// aapt resource value: 0x7f01001a
			public const int sc_crosshairTooltipTextSize = 2130771994;
			
			// aapt resource value: 0x7f01000c
			public const int sc_dashedGridLines = 2130771980;
			
			// aapt resource value: 0x7f01003f
			public const int sc_defaultCrustColor = 2130772031;
			
			// aapt resource value: 0x7f01001e
			public const int sc_defaultSelectedSeriesColor = 2130771998;
			
			// aapt resource value: 0x7f010040
			public const int sc_donutCrustThickness = 2130772032;
			
			// aapt resource value: 0x7f010043
			public const int sc_financialFallingColor = 2130772035;
			
			// aapt resource value: 0x7f010042
			public const int sc_financialRisingColor = 2130772034;
			
			// aapt resource value: 0x7f01000a
			public const int sc_gridLineColor = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int sc_gridStripeColor = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int sc_legendBackgroundColor = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int sc_legendBorderColor = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int sc_legendTextColor = 2130771984;
			
			// aapt resource value: 0x7f01001d
			public const int sc_lineWidth = 2130771997;
			
			// aapt resource value: 0x7f010039
			public const int sc_pieDonutFlavorColor1 = 2130772025;
			
			// aapt resource value: 0x7f01003a
			public const int sc_pieDonutFlavorColor2 = 2130772026;
			
			// aapt resource value: 0x7f01003b
			public const int sc_pieDonutFlavorColor3 = 2130772027;
			
			// aapt resource value: 0x7f01003c
			public const int sc_pieDonutFlavorColor4 = 2130772028;
			
			// aapt resource value: 0x7f01003d
			public const int sc_pieDonutFlavorColor5 = 2130772029;
			
			// aapt resource value: 0x7f01003e
			public const int sc_pieDonutFlavorColor6 = 2130772030;
			
			// aapt resource value: 0x7f010041
			public const int sc_pieDonutLabelColor = 2130772033;
			
			// aapt resource value: 0x7f010002
			public const int sc_plotAreaColor = 2130771970;
			
			// aapt resource value: 0x7f010022
			public const int sc_seriesAreaColor1 = 2130772002;
			
			// aapt resource value: 0x7f010026
			public const int sc_seriesAreaColor2 = 2130772006;
			
			// aapt resource value: 0x7f01002a
			public const int sc_seriesAreaColor3 = 2130772010;
			
			// aapt resource value: 0x7f01002e
			public const int sc_seriesAreaColor4 = 2130772014;
			
			// aapt resource value: 0x7f010032
			public const int sc_seriesAreaColor5 = 2130772018;
			
			// aapt resource value: 0x7f010036
			public const int sc_seriesAreaColor6 = 2130772022;
			
			// aapt resource value: 0x7f010023
			public const int sc_seriesAreaGradientColor1 = 2130772003;
			
			// aapt resource value: 0x7f010027
			public const int sc_seriesAreaGradientColor2 = 2130772007;
			
			// aapt resource value: 0x7f01002b
			public const int sc_seriesAreaGradientColor3 = 2130772011;
			
			// aapt resource value: 0x7f01002f
			public const int sc_seriesAreaGradientColor4 = 2130772015;
			
			// aapt resource value: 0x7f010033
			public const int sc_seriesAreaGradientColor5 = 2130772019;
			
			// aapt resource value: 0x7f010037
			public const int sc_seriesAreaGradientColor6 = 2130772023;
			
			// aapt resource value: 0x7f010024
			public const int sc_seriesAreaGradientTransparentColor1 = 2130772004;
			
			// aapt resource value: 0x7f010028
			public const int sc_seriesAreaGradientTransparentColor2 = 2130772008;
			
			// aapt resource value: 0x7f01002c
			public const int sc_seriesAreaGradientTransparentColor3 = 2130772012;
			
			// aapt resource value: 0x7f010030
			public const int sc_seriesAreaGradientTransparentColor4 = 2130772016;
			
			// aapt resource value: 0x7f010034
			public const int sc_seriesAreaGradientTransparentColor5 = 2130772020;
			
			// aapt resource value: 0x7f010038
			public const int sc_seriesAreaGradientTransparentColor6 = 2130772024;
			
			// aapt resource value: 0x7f010021
			public const int sc_seriesLineColor1 = 2130772001;
			
			// aapt resource value: 0x7f010025
			public const int sc_seriesLineColor2 = 2130772005;
			
			// aapt resource value: 0x7f010029
			public const int sc_seriesLineColor3 = 2130772009;
			
			// aapt resource value: 0x7f01002d
			public const int sc_seriesLineColor4 = 2130772013;
			
			// aapt resource value: 0x7f010031
			public const int sc_seriesLineColor5 = 2130772017;
			
			// aapt resource value: 0x7f010035
			public const int sc_seriesLineColor6 = 2130772021;
			
			// aapt resource value: 0x7f01000b
			public const int sc_showGridLines = 2130771979;
			
			// aapt resource value: 0x7f01000d
			public const int sc_showGridStripes = 2130771981;
			
			// aapt resource value: 0x7f010009
			public const int sc_tickLabelColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int sc_tickLineColor = 2130771976;
			
			// aapt resource value: 0x7f010004
			public const int sc_titleMargin = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int sc_titlePadding = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f040001
			public const int sc_darkShowGridLines = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int sc_dashedGridLines = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int sc_defaultShowGridLines = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int sc_showGridStripes = 2130968579;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05002a
			public const int sc_annotationDarkBackgroundColor = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int sc_annotationDarkTextColor = 2131034155;
			
			// aapt resource value: 0x7f050015
			public const int sc_annotationDefaultBackgroundColor = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int sc_annotationDefaultTextColor = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int sc_axisDarkTitleColor = 2131034136;
			
			// aapt resource value: 0x7f050002
			public const int sc_axisDefaultLineColor = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int sc_axisDefaultTitleColor = 2131034113;
			
			// aapt resource value: 0x7f050030
			public const int sc_blueDark = 2131034160;
			
			// aapt resource value: 0x7f050032
			public const int sc_blueDarkFill = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int sc_blueDarkFillAlpha = 2131034163;
			
			// aapt resource value: 0x7f050031
			public const int sc_blueLightFill = 2131034161;
			
			// aapt resource value: 0x7f05001c
			public const int sc_chartDarkBackgroundColor = 2131034140;
			
			// aapt resource value: 0x7f050017
			public const int sc_chartDarkTitleColor = 2131034135;
			
			// aapt resource value: 0x7f050007
			public const int sc_chartDefaultBackgroundColor = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int sc_chartDefaultTitleColor = 2131034112;
			
			// aapt resource value: 0x7f050023
			public const int sc_crosshairDarkLineColor = 2131034147;
			
			// aapt resource value: 0x7f05000e
			public const int sc_crosshairDefaultLineColor = 2131034126;
			
			// aapt resource value: 0x7f050026
			public const int sc_crosshairTooltipDarkBackgroundColor = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int sc_crosshairTooltipDarkBorderColor = 2131034151;
			
			// aapt resource value: 0x7f050025
			public const int sc_crosshairTooltipDarkLabelBackgroundColor = 2131034149;
			
			// aapt resource value: 0x7f050024
			public const int sc_crosshairTooltipDarkTextColor = 2131034148;
			
			// aapt resource value: 0x7f050011
			public const int sc_crosshairTooltipDefaultBackgroundColor = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int sc_crosshairTooltipDefaultBorderColor = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int sc_crosshairTooltipDefaultLabelBackgroundColor = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int sc_crosshairTooltipDefaultTextColor = 2131034127;
			
			// aapt resource value: 0x7f05004a
			public const int sc_crustColor = 2131034186;
			
			// aapt resource value: 0x7f050029
			public const int sc_darkAlternateGridStripeColor = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int sc_darkGridStripeColor = 2131034152;
			
			// aapt resource value: 0x7f050014
			public const int sc_defaultAlternateGridStripeColor = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int sc_defaultGridStripeColor = 2131034131;
			
			// aapt resource value: 0x7f050006
			public const int sc_defaultSelectedSeriesColor = 2131034118;
			
			// aapt resource value: 0x7f05004d
			public const int sc_financialBlue = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int sc_financialBlueAlpha = 2131034190;
			
			// aapt resource value: 0x7f05004b
			public const int sc_financialGreen = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int sc_financialRed = 2131034188;
			
			// aapt resource value: 0x7f050038
			public const int sc_greenDark = 2131034168;
			
			// aapt resource value: 0x7f05003a
			public const int sc_greenDarkFill = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int sc_greenDarkFillAlpha = 2131034171;
			
			// aapt resource value: 0x7f050039
			public const int sc_greenLightFill = 2131034169;
			
			// aapt resource value: 0x7f05001b
			public const int sc_gridDarkLineColor = 2131034139;
			
			// aapt resource value: 0x7f050005
			public const int sc_gridDefaultLineColor = 2131034117;
			
			// aapt resource value: 0x7f050022
			public const int sc_legendDarkBackgroundColor = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int sc_legendDarkBorderColor = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int sc_legendDarkTextColor = 2131034144;
			
			// aapt resource value: 0x7f05000d
			public const int sc_legendDefaultBackgroundColor = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int sc_legendDefaultBorderColor = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int sc_legendDefaultTextColor = 2131034123;
			
			// aapt resource value: 0x7f050034
			public const int sc_orangeDark = 2131034164;
			
			// aapt resource value: 0x7f050036
			public const int sc_orangeDarkFill = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int sc_orangeDarkFillAlpha = 2131034167;
			
			// aapt resource value: 0x7f050035
			public const int sc_orangeLightFill = 2131034165;
			
			// aapt resource value: 0x7f05001f
			public const int sc_pieDonutLabelDarkColor = 2131034143;
			
			// aapt resource value: 0x7f05000a
			public const int sc_pieDonutLabelDefaultColor = 2131034122;
			
			// aapt resource value: 0x7f050040
			public const int sc_pinkDark = 2131034176;
			
			// aapt resource value: 0x7f050042
			public const int sc_pinkDarkFill = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int sc_pinkDarkFillAlpha = 2131034179;
			
			// aapt resource value: 0x7f050041
			public const int sc_pinkLightFill = 2131034177;
			
			// aapt resource value: 0x7f05001e
			public const int sc_plotDarkAreaBorderColor = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int sc_plotDarkAreaColor = 2131034141;
			
			// aapt resource value: 0x7f050009
			public const int sc_plotDefaultAreaBorderColor = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int sc_plotDefaultAreaColor = 2131034120;
			
			// aapt resource value: 0x7f05002c
			public const int sc_purpleDark = 2131034156;
			
			// aapt resource value: 0x7f05002e
			public const int sc_purpleDarkFill = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int sc_purpleDarkFillAlpha = 2131034159;
			
			// aapt resource value: 0x7f05002d
			public const int sc_purpleLightFill = 2131034157;
			
			// aapt resource value: 0x7f050045
			public const int sc_radialBlue = 2131034181;
			
			// aapt resource value: 0x7f050047
			public const int sc_radialGreen = 2131034183;
			
			// aapt resource value: 0x7f050046
			public const int sc_radialOrange = 2131034182;
			
			// aapt resource value: 0x7f050049
			public const int sc_radialPink = 2131034185;
			
			// aapt resource value: 0x7f050044
			public const int sc_radialPurple = 2131034180;
			
			// aapt resource value: 0x7f050048
			public const int sc_radialYellow = 2131034184;
			
			// aapt resource value: 0x7f05001a
			public const int sc_tickDarkLabelColor = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int sc_tickDarkLineColor = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int sc_tickDefaultLabelColor = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int sc_tickDefaultLineColor = 2131034115;
			
			// aapt resource value: 0x7f05003c
			public const int sc_yellowDark = 2131034172;
			
			// aapt resource value: 0x7f05003e
			public const int sc_yellowDarkFill = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int sc_yellowDarkFillAlpha = 2131034175;
			
			// aapt resource value: 0x7f05003d
			public const int sc_yellowLightFill = 2131034173;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int sc_axisTitleTextSize = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int sc_defaultAnnotationTextSize = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int sc_defaultBarLineWidth = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int sc_defaultColumnLineWidth = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int sc_defaultCrosshairLineWidth = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int sc_defaultCrosshairPadding = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int sc_defaultCrosshairTooltipBorderWidth = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int sc_defaultCrosshairTooltipCornerRadius = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int sc_defaultCrosshairTooltipTextSize = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int sc_defaultDonutCrustThickness = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int sc_defaultLineWidth = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int sc_defaultTitleMargin = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int sc_defaultTitlePadding = 2131099658;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int myButton = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070003
			public const int AnnotationCannotConvertNullX = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int AnnotationCannotConvertNullY = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int AnnotationCannotHaveNullX = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AnnotationCannotHaveNullY = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int AnnotationCannotHaveSameXY = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int AnnotationMustBeOnSameChart = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int AxisDataPointsNotNull = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int AxisDefaultRangeIsEmpty = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int AxisInsufficientWidth = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int AxisNullCustomTickMarkValues = 2131165198;
			
			// aapt resource value: 0x7f070008
			public const int AxisNullMajorTickFrequency = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int AxisRangeNotSetPixelCall = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int AxisRangeNotSetUserCall = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int AxisUndefinedRange = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int AxisUnrecognisedOrientation = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int BandSeriesBaselineNotApplicable = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int CandlestickSeriesBaselineNotApplicable = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int CartesianBaselineWrongType = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int CartesianCannotAddPoint = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int CartesianInvalidDataXY = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int CartesianNeedMultiValueData = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int CategoryAxisIgnoresCustomTickValues = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int CategoryAxisSeriesAlreadyContainsPoint = 2131165205;
			
			// aapt resource value: 0x7f070020
			public const int ChartAlreadyHasThisAxis = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int ChartAxisBelongsToAnotherChart = 2131165217;
			
			// aapt resource value: 0x7f07001f
			public const int ChartCannotAddNullAxis = 2131165215;
			
			// aapt resource value: 0x7f070017
			public const int ChartCannotAddNullSeries = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int ChartCartesianInPieDonut = 2131165210;
			
			// aapt resource value: 0x7f07001e
			public const int ChartFailedToCloseInputStream = 2131165214;
			
			// aapt resource value: 0x7f07001b
			public const int ChartNoPrimaryX = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int ChartNoPrimaryY = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int ChartNoVersionProperties = 2131165213;
			
			// aapt resource value: 0x7f070019
			public const int ChartPieDonutCannotHaveAxes = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int ChartPieDonutInCartesian = 2131165208;
			
			// aapt resource value: 0x7f070022
			public const int ChartPremiumOnly = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int ChartRendererExceptionInGL = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int CrosshairNullFocus = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int CrosshairNullXOrYInFocusPoint = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int DateTimeAxisInvalidDateFrequency = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int NumberAxisInvalidFrequency = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int OHLCSeriesBaselineNotApplicable = 2131165224;
			
			// aapt resource value: 0x7f07002a
			public const int PieDonutSeriesInvalidData = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int PieDonutSeriesYDataMustBePositive = 2131165227;
			
			// aapt resource value: 0x7f07002d
			public const int RangeManagerInvalidRangeRequested = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int RangeManagerLimitsCannotBeNaN = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int RangeManagerNonPositiveSpan = 2131165231;
			
			// aapt resource value: 0x7f07002c
			public const int RangeManagerUnableToSetRange = 2131165228;
			
			// aapt resource value: 0x7f070031
			public const int SeriesDataPointOutOfRange = 2131165233;
			
			// aapt resource value: 0x7f070030
			public const int SeriesNullDataAdapter = 2131165232;
			
			// aapt resource value: 0x7f070032
			public const int SeriesStyleIsNull = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int StackSeriesIteratorOrdinatesOutofOrder = 2131165235;
			
			// aapt resource value: 0x7f070029
			public const int TickMarkManagerNoGhosts = 2131165225;
			
			// aapt resource value: 0x7f070034
			public const int TooltipNullCenter = 2131165236;
			
			// aapt resource value: 0x7f070037
			public const int TooltipNullDataPoint = 2131165239;
			
			// aapt resource value: 0x7f070036
			public const int TooltipNullView = 2131165238;
			
			// aapt resource value: 0x7f070035
			public const int TooltipNullXOrYInCenterPoint = 2131165237;
			
			// aapt resource value: 0x7f070039
			public const int app_name = 2131165241;
			
			// aapt resource value: 0x7f070038
			public const int hello = 2131165240;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_Default = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int Theme_Default_Dark = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int Theme_Default_Light = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ChartTheme = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039,
					2130772040,
					2130772041,
					2130772042};
			
			// aapt resource value: 15
			public const int ChartTheme_sc_alternateGridStripeColor = 15;
			
			// aapt resource value: 72
			public const int ChartTheme_sc_annotationBackgroundColor = 72;
			
			// aapt resource value: 73
			public const int ChartTheme_sc_annotationTextColor = 73;
			
			// aapt resource value: 74
			public const int ChartTheme_sc_annotationTextSize = 74;
			
			// aapt resource value: 7
			public const int ChartTheme_sc_axisLineColor = 7;
			
			// aapt resource value: 5
			public const int ChartTheme_sc_axisTitleColor = 5;
			
			// aapt resource value: 6
			public const int ChartTheme_sc_axisTitleTextSize = 6;
			
			// aapt resource value: 70
			public const int ChartTheme_sc_bandSeriesAreaColor = 70;
			
			// aapt resource value: 71
			public const int ChartTheme_sc_bandSeriesAreaInvertedColor = 71;
			
			// aapt resource value: 68
			public const int ChartTheme_sc_bandSeriesHighColor = 68;
			
			// aapt resource value: 69
			public const int ChartTheme_sc_bandSeriesLowColor = 69;
			
			// aapt resource value: 32
			public const int ChartTheme_sc_barLineWidth = 32;
			
			// aapt resource value: 1
			public const int ChartTheme_sc_chartBackgroundColor = 1;
			
			// aapt resource value: 0
			public const int ChartTheme_sc_chartTitleColor = 0;
			
			// aapt resource value: 31
			public const int ChartTheme_sc_columnLineWidth = 31;
			
			// aapt resource value: 19
			public const int ChartTheme_sc_crosshairLineColor = 19;
			
			// aapt resource value: 24
			public const int ChartTheme_sc_crosshairLineWidth = 24;
			
			// aapt resource value: 25
			public const int ChartTheme_sc_crosshairPadding = 25;
			
			// aapt resource value: 22
			public const int ChartTheme_sc_crosshairTooltipBackgroundColor = 22;
			
			// aapt resource value: 23
			public const int ChartTheme_sc_crosshairTooltipBorderColor = 23;
			
			// aapt resource value: 28
			public const int ChartTheme_sc_crosshairTooltipBorderWidth = 28;
			
			// aapt resource value: 27
			public const int ChartTheme_sc_crosshairTooltipCornerRadius = 27;
			
			// aapt resource value: 21
			public const int ChartTheme_sc_crosshairTooltipLabelBackgroundColor = 21;
			
			// aapt resource value: 20
			public const int ChartTheme_sc_crosshairTooltipTextColor = 20;
			
			// aapt resource value: 26
			public const int ChartTheme_sc_crosshairTooltipTextSize = 26;
			
			// aapt resource value: 12
			public const int ChartTheme_sc_dashedGridLines = 12;
			
			// aapt resource value: 63
			public const int ChartTheme_sc_defaultCrustColor = 63;
			
			// aapt resource value: 30
			public const int ChartTheme_sc_defaultSelectedSeriesColor = 30;
			
			// aapt resource value: 64
			public const int ChartTheme_sc_donutCrustThickness = 64;
			
			// aapt resource value: 67
			public const int ChartTheme_sc_financialFallingColor = 67;
			
			// aapt resource value: 66
			public const int ChartTheme_sc_financialRisingColor = 66;
			
			// aapt resource value: 10
			public const int ChartTheme_sc_gridLineColor = 10;
			
			// aapt resource value: 14
			public const int ChartTheme_sc_gridStripeColor = 14;
			
			// aapt resource value: 18
			public const int ChartTheme_sc_legendBackgroundColor = 18;
			
			// aapt resource value: 17
			public const int ChartTheme_sc_legendBorderColor = 17;
			
			// aapt resource value: 16
			public const int ChartTheme_sc_legendTextColor = 16;
			
			// aapt resource value: 29
			public const int ChartTheme_sc_lineWidth = 29;
			
			// aapt resource value: 57
			public const int ChartTheme_sc_pieDonutFlavorColor1 = 57;
			
			// aapt resource value: 58
			public const int ChartTheme_sc_pieDonutFlavorColor2 = 58;
			
			// aapt resource value: 59
			public const int ChartTheme_sc_pieDonutFlavorColor3 = 59;
			
			// aapt resource value: 60
			public const int ChartTheme_sc_pieDonutFlavorColor4 = 60;
			
			// aapt resource value: 61
			public const int ChartTheme_sc_pieDonutFlavorColor5 = 61;
			
			// aapt resource value: 62
			public const int ChartTheme_sc_pieDonutFlavorColor6 = 62;
			
			// aapt resource value: 65
			public const int ChartTheme_sc_pieDonutLabelColor = 65;
			
			// aapt resource value: 2
			public const int ChartTheme_sc_plotAreaColor = 2;
			
			// aapt resource value: 34
			public const int ChartTheme_sc_seriesAreaColor1 = 34;
			
			// aapt resource value: 38
			public const int ChartTheme_sc_seriesAreaColor2 = 38;
			
			// aapt resource value: 42
			public const int ChartTheme_sc_seriesAreaColor3 = 42;
			
			// aapt resource value: 46
			public const int ChartTheme_sc_seriesAreaColor4 = 46;
			
			// aapt resource value: 50
			public const int ChartTheme_sc_seriesAreaColor5 = 50;
			
			// aapt resource value: 54
			public const int ChartTheme_sc_seriesAreaColor6 = 54;
			
			// aapt resource value: 35
			public const int ChartTheme_sc_seriesAreaGradientColor1 = 35;
			
			// aapt resource value: 39
			public const int ChartTheme_sc_seriesAreaGradientColor2 = 39;
			
			// aapt resource value: 43
			public const int ChartTheme_sc_seriesAreaGradientColor3 = 43;
			
			// aapt resource value: 47
			public const int ChartTheme_sc_seriesAreaGradientColor4 = 47;
			
			// aapt resource value: 51
			public const int ChartTheme_sc_seriesAreaGradientColor5 = 51;
			
			// aapt resource value: 55
			public const int ChartTheme_sc_seriesAreaGradientColor6 = 55;
			
			// aapt resource value: 36
			public const int ChartTheme_sc_seriesAreaGradientTransparentColor1 = 36;
			
			// aapt resource value: 40
			public const int ChartTheme_sc_seriesAreaGradientTransparentColor2 = 40;
			
			// aapt resource value: 44
			public const int ChartTheme_sc_seriesAreaGradientTransparentColor3 = 44;
			
			// aapt resource value: 48
			public const int ChartTheme_sc_seriesAreaGradientTransparentColor4 = 48;
			
			// aapt resource value: 52
			public const int ChartTheme_sc_seriesAreaGradientTransparentColor5 = 52;
			
			// aapt resource value: 56
			public const int ChartTheme_sc_seriesAreaGradientTransparentColor6 = 56;
			
			// aapt resource value: 33
			public const int ChartTheme_sc_seriesLineColor1 = 33;
			
			// aapt resource value: 37
			public const int ChartTheme_sc_seriesLineColor2 = 37;
			
			// aapt resource value: 41
			public const int ChartTheme_sc_seriesLineColor3 = 41;
			
			// aapt resource value: 45
			public const int ChartTheme_sc_seriesLineColor4 = 45;
			
			// aapt resource value: 49
			public const int ChartTheme_sc_seriesLineColor5 = 49;
			
			// aapt resource value: 53
			public const int ChartTheme_sc_seriesLineColor6 = 53;
			
			// aapt resource value: 11
			public const int ChartTheme_sc_showGridLines = 11;
			
			// aapt resource value: 13
			public const int ChartTheme_sc_showGridStripes = 13;
			
			// aapt resource value: 9
			public const int ChartTheme_sc_tickLabelColor = 9;
			
			// aapt resource value: 8
			public const int ChartTheme_sc_tickLineColor = 8;
			
			// aapt resource value: 4
			public const int ChartTheme_sc_titleMargin = 4;
			
			// aapt resource value: 3
			public const int ChartTheme_sc_titlePadding = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
